apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-account.yaml
  - redis.yaml
  - redis-exporter.yaml
  - multichain-node-configmap.yaml
  - multichain-node-deployment.yaml
  - multichain-node-service.yaml
  - multichain-node-operator-rbac.yaml
  - multichain-node-operator.yaml
