apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: multichain-node-secrets
  namespace: chain-sig
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gsm-secret-store
  target:
    name: multichain-node-secrets
    creationPolicy: Owner
  data:
    - secretKey: MPC_ACCOUNT_SK
      remoteRef:
        key: multichain-account-sk-mainnet-0
    - secretKey: MPC_CIPHER_SK
      remoteRef:
        key: multichain-cipher-sk-mainnet-0
    - secretKey: MPC_SIGN_SK
      remoteRef:
        key: multichain-sign-sk-mainnet-0
    - secretKey: MPC_ETH_ACCOUNT_SK
      remoteRef:
        key: multichain-eth-account-sk-mainnet-0
    - secretKey: MPC_ETH_EXECUTION_RPC_HTTP_URL
      remoteRef:
        key: multichain-eth-execution-rpc-url-mainnet
    - secretKey: MPC_ETH_CONSENSUS_RPC_HTTP_URL
      remoteRef:
        key: multichain-eth-consensus-rpc-url-mainnet
    - secretKey: MPC_SOL_ACCOUNT_SK
      remoteRef:
        key: multichain-sol-account-sk-mainnet-0
    - secretKey: MPC_SOL_RPC_HTTP_URL
      remoteRef:
        key: multichain-sol-rpc-http-url-mainnet
    - secretKey: MPC_SOL_RPC_WS_URL
      remoteRef:
        key: multichain-sol-rpc-ws-url-mainnet
    - secretKey: MPC_HYDRATION_RPC_WS_URL
      remoteRef:
        key: multichain-hydration-rpc-ws-url-mainnet
    - secretKey: MPC_HYDRATION_SIGNER_URI
      remoteRef:
        key: multichain-hydration-signer-uri-mainnet
