apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-account.yaml
  - redis.yaml
  - redis-exporter.yaml
  - multichain-testnet-8-configmap.yaml
  - multichain-testnet-8-deployment.yaml
  - multichain-testnet-8-service.yaml
  - multichain-testnet-8-operator-rbac.yaml
  - multichain-testnet-8-operator.yaml
