apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: multichain-testnet-8-secrets
  namespace: chain-sig
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gsm-secret-store
  target:
    name: multichain-testnet-8-secrets
    creationPolicy: Owner
  data:
    - secretKey: MPC_ACCOUNT_SK
      remoteRef:
        key: multichain-account-sk-testnet-8
    - secretKey: MPC_CIPHER_SK
      remoteRef:
        key: multichain-cipher-sk-testnet-8
    - secretKey: MPC_SIGN_SK
      remoteRef:
        key: multichain-sign-sk-testnet-8
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: multichain-indexer-aws-access-key
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: multichain-indexer-aws-secret-key
    - secretKey: MPC_ETH_ACCOUNT_SK
      remoteRef:
        key: multichain-eth-account-sk-testnet-8
    - secretKey: MPC_ETH_EXECUTION_RPC_HTTP_URL
      remoteRef:
        key: multichain-eth-execution-rpc-url-testnet
    - secretKey: MPC_ETH_CONSENSUS_RPC_HTTP_URL
      remoteRef:
        key: multichain-eth-consensus-rpc-url-testnet
    - secretKey: MPC_SOL_ACCOUNT_SK
      remoteRef:
        key: multichain-sol-account-sk-testnet
    - secretKey: MPC_SOL_RPC_HTTP_URL
      remoteRef:
        key: multichain-sol-rpc-http-url-testnet
    - secretKey: MPC_SOL_RPC_WS_URL
      remoteRef:
        key: multichain-sol-rpc-ws-url-testnet
    - secretKey: MPC_CANTON_OIDC_TOKEN_URL
      remoteRef:
        key: multichain-canton-oidc-token-url-testnet
    - secretKey: MPC_CANTON_OIDC_CLIENT_ID
      remoteRef:
        key: multichain-canton-oidc-client-id-testnet
    - secretKey: MPC_CANTON_OIDC_CLIENT_SECRET
      remoteRef:
        key: multichain-canton-oidc-client-secret-testnet
    - secretKey: MPC_CANTON_OIDC_AUDIENCE
      remoteRef:
        key: multichain-canton-oidc-audience-testnet
