apiVersion: apps/v1
kind: Deployment
metadata:
  name: multichain-testnet-8
  namespace: chain-sig
  labels:
    app: multichain-8
    deploy: multichain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multichain-8
  template:
    metadata:
      labels:
        app: multichain-8
        deploy: multichain
    spec:
      serviceAccountName: k8s-sa
      containers:
        - name: multichain-8
          image: europe-west1-docker.pkg.dev/near-cs-testnet/multichain-public/multichain-testnet:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1500m
              memory: 1200Mi
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: multichain-testnet-8-config
            - secretRef:
                name: multichain-testnet-8-secrets
