apiVersion: v1
kind: Secret
metadata:
  name: multichain-testnet-secrets
  namespace: multichain-testnet
type: Opaque
stringData:
  MPC_ACCOUNT_SK: <replace-me>
  MPC_CIPHER_SK: <replace-me>
  MPC_SIGN_SK: <replace-me>
  MPC_ETH_ACCOUNT_SK: <replace-me>
  MPC_SOL_ACCOUNT_SK: <replace-me>
  MPC_ETH_CONSENSUS_RPC_HTTP_URL: <replace-me>
  MPC_ETH_EXECUTION_RPC_HTTP_URL: <replace-me>
  MPC_SOL_RPC_HTTP_URL: <replace-me>
  MPC_SOL_RPC_WS_URL: <replace-me>
